server:
  port: 8700 #服务端口号
spring:
  application:
    name: gateway  #微服务名称，对外暴漏的微服务名称，十分重要
  cloud:
    gateway: #网关路由配置
      routes:
        - id: router-client   #路由 id,没有固定规则，但唯一，建议与服务名对应
          # uri: http://localhost:8550          #匹配后提供服务的路由地址
          uri: lb://eureka-client
          predicates:
            - Path=/get
          filters:
            - PrefixPath=/eureka #在请求路径上增加一个前缀 /eureka

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server-00:8400/eureka/
  instance:
    instance-id: gateway-server
    prefer-ip-address: true
    hostname: gateway-server