# 端口配置
server:
  port: 8300

# Spring配置
spring:
  application:
    name:mybatis-plus-00
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password:

# MyBatis-plus配置
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: org.example.mapper.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl