# 端口配置
server:
  port: 9060

# 应用名称
spring:
  application:
    name: seata-storage-06
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seata_storage?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password:
  cloud:
    alibaba:
      seata:
        tx-service-group: service-storage-group
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 #nacos 服务器地址
        namespace: public #nacos 命名空间
        username: nacos
        password: nacos
    sentinel:
      transport:
        dashboard: 127.0.0.1:8080  #Sentinel 控制台地址
        port: 8719

seata:
  application-id: ${spring.application.name}
  tx-service-group: service-storage-group
  service:
    grouplist:
      seata-server: 127.0.0.1:8091
  registry:
    type: nacos
    nacos:
      server-addr: 127.0.0.1:8848 # Nacos 配置中心的地址
  config:
    type: nacos
    nacos:
      server-addr: 127.0.0.1:8848 # Nacos 配置中心的地址

feign:
  sentinel:
    enabled: true #开启 OpenFeign 功能

management:
  endpoints:
    web:
      exposure:
        include: "*"

# MyBatis-plus配置
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: org.example.mapper.entity
  configuration:
    #默认开启驼峰命名法，可以不用设置该属性
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl