# 端口配置
server:
  port: 9000

# 应用名称
spring:
  application:
    name: seata-client-00
  profiles:
    active: dev #激活 dev 的配置
  alibaba:
    seata:
      tx-service-group: service-order-group  #事务分组名

seata:
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: 127.0.0.1:8848 # Nacos 配置中心的地址
      group : "SEATA_GROUP"  #分组
      namespace: ""
      username: "nacos"   #Nacos 配置中心的用于名
      password: "nacos"  #Nacos 配置中心的密码
  config:
    type: nacos
    nacos:
      server-addr: 127.0.0.1:8848 # Nacos 配置中心的地址
      group: "SEATA_GROUP"  #分组
      namespace: ""
      username: "nacos"   #Nacos 配置中心的用于名
      password: "nacos"  #Nacos 配置中心的密码